/* ****************************************************************************** *\

Author : Qiushi Yuan
Copyright(c) 2008-2015 Qiushi Yuan. All Rights Reserved.
This software is supplied under the terms, you cannot copy or disclose except agreement with the author. 

\* ****************************************************************************** */
#ifndef __INC_YXC_SYS_BASE_ERROR_CODE_H__
#define __INC_YXC_SYS_BASE_ERROR_CODE_H__

/* 3rd Error categories. */
#define YXC_ERR_CAT_3RD_FFMPEG 1
#define YXC_ERR_CAT_3RD_CUDA 2
#define YXC_ERR_CAT_3RD_MARKUP 3
#define YXC_ERR_CAT_3RD_NVENC 4
#define YXC_ERR_CAT_3RD_MFX 5
#define YXC_ERR_CAT_3RD_JSON 6
#define YXC_ERR_CAT_3RD_WEBRTC 7

/* OS Error categories */
#define YXC_ERR_CAT_OS_LRESULT 0
#define YXC_ERR_CAT_OS_HRESULT 1
#define YXC_ERR_CAT_OS_WSA 2
#define YXC_ERR_CAT_OS_ERRNO 3
#define YXC_ERR_CAT_OS_MMSYSTEM 4

/* SQL Error categories */
#define YXC_ERR_CAT_SQL_ODBC 0
#define YXC_ERR_CAT_SQL_MYSQL 1
#define YXC_ERR_CAT_SQL_SQLITE 2

/* External error categories */
#define YXC_ERR_CAT_3RD_APP 0
#define YXC_ERR_CAT_3RD_DLL 1

/* -200000 ~ 0 - YXC System Error */
#define YXC_ERC_SUCCESS 0

#define YXC_ERC_UNKNOWN (-1)
#define YXC_ERC_OS (-2)
#define YXC_ERC_C_RUNTIME (-3)
#define YXC_ERC_NO_ERROR (-4)
#define YXC_ERC_EXT (-5)
#define YXC_ERC_SQL (-6)
#define YXC_ERC_3RD (-7)

#define YXC_ERC_INVALID_PARAMETER (-9)
#define YXC_ERC_NOT_SUPPORTED (-10)
#define YXC_ERC_OUT_OF_MEMORY (-11)
#define YXC_ERC_INDEX_OUT_OF_RANGE (-12)
#define YXC_ERC_BUFFER_NOT_ENOUGH (-13)
#define YXC_ERC_TIMEOUT (-14)
#define YXC_ERC_EXCEED_MAX_COUNT (-15)
#define YXC_ERC_CLOSED_HANDLE (-16)
#define YXC_ERC_INVALID_HANDLE (-17)
#define YXC_ERC_INVALID_OPERATION (-18)
#define YXC_ERC_LOG_LOW_LEVEL (-19)
#define YXC_ERC_KEY_NOT_FOUND (-20)
#define YXC_ERC_INVALID_PASSWORD (-21)
#define YXC_ERC_NO_DATA (-22)
#define YXC_ERC_DATA_TRUNCATED (-23)
#define YXC_ERC_INVALID_TYPE (-24)
#define YXC_ERC_FRACTION_TRUNCATED (-25)
#define YXC_ERC_PROC_NOT_FOUND (-26)
#define YXC_ERC_NOT_INITIALIZED (-27)

#define YXC_ERC_WAIT_ABANDONED (-28)
#define YXC_ERC_KEY_NOT_UNIQUE (-29)
#define YXC_ERC_INVALID_STATUS (-30)
#define YXC_ERC_STILL_ALIVE (-31)
#define YXC_ERC_OPERATION_CANCELED (-32)
#define YXC_ERC_USER_HAS_LOGINED (-33)
#define YXC_ERC_NO_RES_AVAILABLE (-34)
#define YXC_ERC_REMOTE_ERROR (-35)
#define YXC_ERC_PATH_NOT_FOUND (-36)
#define YXC_ERC_INVALID_FILE_FORMAT (-37)
#define YXC_ERC_EOF (-38)
#define YXC_ERC_ACCESS_DENIED (-39)
#define YXC_ERC_OUT_OF_DISK_SPACE (-40)
#define YXC_ERC_IO_INCOMPLETED (-41)
#define YXC_ERC_NEED_SAVEAS (-42)
#define YXC_ERC_INVALID_POINTER (-43)
#define YXC_ERC_DEV_IN_USE (-44)
#define YXC_ERC_INCOMPATABLE_FILE_FORMAT (-45)
#define YXC_ERC_INVALID_VERSION (-46)
#define YXC_ERC_ALREADY_EXISTS (-47)
#define YXC_ERC_INVALID_PATH (-48)
#define YXC_ERC_DEV_INIT_FAILED (-49)
#define YXC_ERC_DUPLICATE_DATA (-59)
#define YXC_ERC_NEED_MORE_DATA (-60)
#define YXC_ERC_NEED_KEY_FRAME (-61)
#define YXC_ERC_STACK_OVERFLOW (-62)
#define YXC_ERC_BAD_VERIFICATION (-64)
#define YXC_ERC_PERMISSION_DENIED (-65)
#define YXC_ERC_INVALID_NUMBER_FORMAT (-66)
#define YXC_ERC_SPEED_CONTROLLED (-67)
#define YXC_ERC_INVALID_URL_FORMAT (-68)

#define YXC_ERC_ALREADY_CREATED (-1000)
#define YXC_ERC_EXT_EVENT_TRIGGERED (-1001)

#define YXC_ERC_MMBASE_NO_FIT_BLOCK (-5000)
#define YXC_ERC_MMBASE_NOT_INIALIZED (-5001)

#define YXC_ERC_PNCMP_CONSUMER_FULL (-10000)
#define YXC_ERC_PNCMP_WAIT_BLOCK_ERROR (-10001)
#define YXC_ERC_PNCMP_EXCEED_MAX_CONSUMERS (-10002)
#define YXC_ERC_PNCMP_NO_CONSUMER (-10003)
#define YXC_ERC_PNCMP_POOL_FULL (-10004)
#define YXC_ERC_PNCMP_PRODUCER_ALIVE (-10005)
#define YXC_ERC_PNCMP_CONSUMER_ALL_FULL (-10006)
#define YXC_ERC_PNCMP_DROP_BLOCK (-10007)

#define YXC_ERC_NET_END_CODE (-20000)
#define YXC_ERC_SOCK_INIT_ENV_FAILED (-20005)
#define	YXC_ERC_SOCK_ADDR_IN_USE (-20006)
#define	YXC_ERC_SOCK_ADDR_NOT_AVAIL (-20007)
#define	YXC_ERC_SOCK_AF_NO_SUPPORT (-20008)
#define	YXC_ERC_SOCK_ALREADY (-20009)
#define	YXC_ERC_SOCK_BAD_MSG (-20010)
#define	YXC_ERC_SOCK_CANCELED (-20011)
#define	YXC_ERC_SOCK_CONN_ABORTED (-20012)
#define	YXC_ERC_SOCK_CONN_REFUSED (-20013)
#define	YXC_ERC_SOCK_CONN_RESET (-20014)
#define	YXC_ERC_SOCK_DEST_ADDR_REQ (-20015)
#define	YXC_ERC_SOCK_HOST_UNREACH (-20016)
#define	YXC_ERC_SOCK_IDRM (-20017)
#define	YXC_ERC_SOCK_IN_PROGRESS (-20018)
#define	YXC_ERC_SOCK_IS_CONN (-20019)
#define	YXC_ERC_SOCK_LOOP (-20020)
#define	YXC_ERC_SOCK_MSG_SIZE (-20021)
#define	YXC_ERC_SOCK_NETWORK_DOWN (-20022)
#define	YXC_ERC_SOCK_NETWORK_RESET (-20023)
#define	YXC_ERC_SOCK_NETWORK_UNREACH (-20024)
#define	YXC_ERC_SOCK_NO_BUFS (-20025)
#define	YXC_ERC_SOCK_NO_DATA (-20026)
#define	YXC_ERC_SOCK_NO_LINK (-20027)
#define	YXC_ERC_SOCK_NO_MSG (-20028)
#define	YXC_ERC_SOCK_NO_PROTO_OPT (-20029)
#define	YXC_ERC_SOCK_NO_SR (-20030)
#define	YXC_ERC_SOCK_NO_STR (-20031)
#define	YXC_ERC_SOCK_NOT_CONN (-20032)
#define	YXC_ERC_SOCK_NOT_RECOVERABLE (-20033)
#define	YXC_ERC_SOCK_NOT_SOCK (-20034)
#define	YXC_ERC_SOCK_NOT_SUP (-20035)
#define	YXC_ERC_SOCK_OP_NOT_SUPP (-20036)
#define	YXC_ERC_SOCK_OTHER (-20037)
#define	YXC_ERC_SOCK_OVERFLOW (-20038)
#define	YXC_ERC_SOCK_OWNER_DEAD (-20039)
#define	YXC_ERC_SOCK_PROTO (-20040)
#define	YXC_ERC_SOCK_PROTO_NO_SUPPORT (-20041)
#define	YXC_ERC_SOCK_PROTO_TYPE (-20042)
#define	YXC_ERC_SOCK_TIME (-20043)
#define	YXC_ERC_SOCK_TIMEDOUT (-20044)
#define	YXC_ERC_SOCK_TEXT_BSY (-20045)
#define	YXC_ERC_SOCK_WOULD_BLOCK (-20046)
#define	YXC_ERC_SOCK_WSA (-20048)

#define YXC_ERC_NET_PACKAGE_TOO_BIG (-20102)
#define YXC_ERC_NET_SHUTDOWN (-20103)
#define YXC_ERC_NET_INVALID_HEADER (-20104)
#define YXC_ERC_NET_CHECKSUM_FAILED (-20105)
#define YXC_ERC_NET_INVALID_PROTOCOL (-20106)
#define YXC_ERC_NET_INVALID_PACKAGE (-20107)
#define YXC_ERC_NET_MANUALLY_CLOSE (-20108)

#define YXC_ERC_P2P_CONNECT_SERVER_FAILED (-20109)

#define YXC_ERC_NPAV_INVALID_PROTOCOL (-21000)
#define YXC_ERC_NET_START_CODE (-29999)

#define YXC_ERC_NET_SRV_CLIENT_ALREADY_INITED (-30001)

/* AV Error codes. */
#define YXC_ERC_AV_VIDEO_PARSE_FAILED (-40100)

#endif /* __INC_YXC_SYS_BASE_ERROR_CODE_H__ */
